# This workflow builds a Unity project that uses the Cesium for Unity package.
# The key change is running the build job on 'windows-latest' to ensure
# compatibility with Cesium's native code components.

name: Build project

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

jobs:
  # This job remains the same. It checks for the necessary Unity license secret.
  checklicense:
    name: Check for UNITY_LICENSE in GitHub Secrets
    runs-on: ubuntu-latest
    outputs:
      is_unity_license_set: ${{ steps.checklicense_job.outputs.is_unity_license_set }}
    steps:
      - name: Check whether Unity activation should be done
        id: checklicense_job
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: |
          if [[ -n "${UNITY_LICENSE}" ]]; then
            echo "is_unity_license_set=true" >> $GITHUB_OUTPUT
          else
            echo "is_unity_license_set=false" >> $GITHUB_OUTPUT
          fi

  # This job now runs on a Windows environment.
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    needs: checklicense
    if: needs.checklicense.outputs.is_unity_license_set == 'true'
    # MODIFICATION: Switched from 'ubuntu-latest' to 'windows-latest'.
    # This is the crucial change to support Cesium for Unity's native components.
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      # Checkout your project repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Cache the Unity Library folder to speed up subsequent builds
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      # Use the GameCI Unity Builder action to build the project.
      # This action works on Windows and will correctly build the project
      # with the Cesium UPM package included.
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      # Upload the finished build as a workflow artifact
      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
