name: release-please

on:
  push:
    branches: [ master ]     # your default branch is master
  workflow_dispatch:         # let you run it manually

permissions:
  contents: write            # create tags & releases
  pull-requests: write       # open the Release PR

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_PAT }}
          command: manifest
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: master
